/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package POO;

import javax.swing.ImageIcon;

/**
 *
 * @author nn
 */
public class Carte extends javax.swing.JPanel {

    /**
     * Creates new form Carte
     */
    String urlFace;
    String urlDos;
    int id;
    public void setUrlFace(String url){
        urlFace=url;
    }
    public void setUrlDos(String url){
        urlDos=url;
    }
    public void setId(int val){
        id=val;
    }
    public int getId(){
        return id;
    }
    private void affichePhoto(String url){
        ImageIcon icon= new ImageIcon(url);
        photoLbl.setIcon(icon);
    }
    public void tournerDos(){
        affichePhoto(urlDos);
    }
    public void tournerFace(){
        affichePhoto(urlFace);
    }
    public Carte(String ud, String uf, int ni) {
        initComponents();
        setUrlDos(ud);
        setUrlFace(uf);
        setId(ni);
        tournerDos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photoLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        photoLbl.setBackground(new java.awt.Color(255, 255, 255));
        photoLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        photoLbl.setOpaque(true);
        photoLbl.setPreferredSize(new java.awt.Dimension(57, 91));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(photoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(photoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel photoLbl;
    // End of variables declaration//GEN-END:variables
}
