/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package POO;

import java.awt.event.MouseEvent;

/**
 *
 * @author nn
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        initCarte();
    }
    public void initCarte(){
        listeCartes=new Carte[nbCartes];
        int cptr = 0;
        for (int i = 0; i < nbCartes; i++) {
            listeCartes[i]= new Carte("photos/dos.png","photos/carte"+cptr+".png",cptr);
            cptr++;
            if (cptr==nbCartes/2) {
                cptr=0;
            }
        }
        //melanger();
        afficheAvecEffet();
    }
    private int hasard(int min,int max){
        double j= Math.random();
        int resultat=(int)((max-min)*j+min);
        return resultat;
    }
    private void melanger(){
        for (int i = 0; i < listeCartes.length; i++) {
             int alea=hasard(0,listeCartes.length);
             Carte tmp = listeCartes[i];
             listeCartes[i]=listeCartes[alea];
             listeCartes[alea]=tmp;
        } 
    }
    private void afficheAvecEffet(){
        for (int i = 0; i < nbCartes; i++) {
            listeCartes[i].addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseReleased(MouseEvent e) {
                    carteMouseReleased(e);
                }   
            });
            boite.add(listeCartes[i]);
        }
    }
    private void carteMouseReleased(MouseEvent e){
        carteCliquee= (Carte) e.getSource();
        if(retourner){
            premiere.tournerDos();
            seconde.tournerDos();
            retourner=false;
        }
        if(nbClick==0){
            nbClick=1;
            premiere=carteCliquee;
            premiere.tournerFace();
            premiere.removeMouseListener(premiere.getMouseListeners()[0]);
        }else{
            nbClick=0;
            seconde=carteCliquee;
            seconde.tournerFace();
            if(premiere.getId()!=seconde.getId()){
                retourner=true;
                premiere.addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseReleased(MouseEvent e) {
                        carteMouseReleased(e);
                    }    
                });
            }else{
                seconde.removeMouseListener(seconde.getMouseListeners()[0]);
                nbPaires+=2;
                if(nbPaires==nbCartes){
                    Message message;
                    message = new Message(this, true);
                    retournerToutesLesCartes();
                    boite.removeAll();
                    initCarte();
                    nbPaires=0;
                }
            }
        }
    }
    private void retournerToutesLesCartes(){
        for (int i = 0; i < listeCartes.length; i++) {
             listeCartes[i].tournerDos();   
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boite = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        boite.setBackground(new java.awt.Color(255, 255, 255));
        boite.setBorder(javax.swing.BorderFactory.createTitledBorder("Jeu de Carte"));
        boite.setLayout(new java.awt.GridLayout(4, 12));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boite, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boite, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    private Carte[] listeCartes;
    private static int nbCartes=48;
    Carte carteCliquee,premiere,seconde;
    int nbClick,nbPaires;
    boolean retourner=false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boite;
    // End of variables declaration//GEN-END:variables
}
